### ISSUE TITLE
Required extents vlr

### ISSUE THREAD

**Issue by davidcaron** [RockRobotic/copc-lib#109]
Hi, 

Thank you for this library, I've been using it for the past few weeks and it's working great.

I was wondering what your plan was for the extents vlr. From what I understand, it's been removed from the spec, but it seems to be required when opening a COPC file. I found a related discussion here: https://github.com/copcio/copcio.github.io/pull/50

I've been working with COPC files generated from Untwine and PDAL, but both of these don't produce an extents vlr, so the following error happens when I try to open the files with copc-lib:

```
RuntimeError: Reader::ReadCopcExtentsVlr: No COPC Extents VLR found in file.
```

To work with these files, I removed the extents vlr entirely in this branch : https://github.com/davidcaron/copc-lib/tree/remove-extents-vlr. 

I guess my question is: did you plan on making the extents vlr optional, or to remove it?

**Comment by leo-stan** [comment]
Hey @davidcaron, thanks for reaching out! That's a bug indeed it should only be optional. We will keep in copc-lib because we think they are useful, but we definitely shouldn't require them. I'll push a fix ASAP.

**Comment by leo-stan** [comment]
Please test PR #110 and let me know if it works correctly :)

**Comment by davidcaron** [comment]
Awesome, it works fine, thanks!

**Comment by CCInc** [comment]
Thanks for the issue. This should be fixed in https://github.com/RockRobotic/copc-lib/releases/tag/v2.3.1 . I will get a new conda/pip deploy out soon.

**Comment by davidcaron** [comment]
That was really fast, thanks for the quick fix and the release!
